# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
