<?php

namespace JTV\CleanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotifiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifiesRepository extends EntityRepository
{
}
